### ISSUE TITLE
Fproc not working with my epic program that i wrote myself (btw i am a god)

### ISSUE THREAD

**Issue by martin-esparragoza** [BlueCannonBall/fproc#2]
OMG OMGOM GOM GO MGOMOMOGMOM OGM OGM OGM OGMO MOGMO M!!!!1111 MY PROGRAM I WROTE IN PYTHON THAT IS 23032103023120312031002012`473417913817481739847138937491834 LINES NO WORK!!111 I RAN ```fproc python3 epicprogramthatissuperexadgerated``` AND I RAN ```fproc list``` AND IT HAVE ERRRORORORO!!!!111 😡 😡 ! THIS IS NOT COOL...d.as.as.as.sa ijo IM GOING TO SUE OYU!111

**Comment by BlueCannonBall** [comment]
Ok sue us.

**Comment by UE2020** [comment]
Can you paste the backtrace here? You can obtain a backtrace by setting the environment variable `RUST_BACKTRACE=1`

**Comment by martin-esparragoza** [comment]
HEY YOU ARE NOT SUPPOSED TO HELP ME JUST DELETE THE ISSUE DUM DUM
